id: IB93A8871
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-27T11:10:07+00:00'
last_modified: '2022-06-08T14:02:37.807008+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W3CN532
  title: ལུང་བསྟན་ཕྱོགས་བཏུས།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    '2998':
      image_group_id: I3CN8541
      title: ''
      total_pages: 498
      order: 1
      base_file: 2998.txt
    ADDA:
      image_group_id: I3CN8542
      title: ''
      total_pages: 480
      order: 2
      base_file: ADDA.txt
    '4000':
      image_group_id: I3CN8543
      title: ''
      total_pages: 490
      order: 3
      base_file: 4000.txt
    9A5A:
      image_group_id: I3CN8544
      title: ''
      total_pages: 488
      order: 4
      base_file: 9A5A.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
