id: IB93A8871
legacy_id: P010498
ocr_import_info:
  bdrc_scan_id: W3CN532
  source: bdrc
  ocr_info:
    timestamp: '2020-03-27T11:06:27'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-08-27T12:06:12.423852+00:00'
last_modified: 2022-08-27 20:07:58.982483
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W3CN532
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  geo_restriction:
  - CN
  reproduction_of: http://purl.bdrc.io/resource/MW3CN532
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: ལུང་བསྟན་ཕྱོགས་བཏུས།
statistics:
  ocr_word_mean_confidence_index: 0.9372009939759107
  ocr_word_median_confidence_index: 0.9700000286102295
quality: null
bases:
  I3CN8544:
    source_metadata:
      id: http://purl.bdrc.io/resource/I3CN8544
      total_pages: 488
      volume_number: 4
      volume_pages_bdrc_intro: 2
    order: 4
    base_file: I3CN8544.txt
    statistics:
      ocr_word_median_confidence_index: 0.9700000286102295
      ocr_word_mean_confidence_index: 0.9327345525730746
    legacy_id: v004
  I3CN8541:
    source_metadata:
      id: http://purl.bdrc.io/resource/I3CN8541
      total_pages: 498
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I3CN8541.txt
    statistics:
      ocr_word_median_confidence_index: 0.9599999785423279
      ocr_word_mean_confidence_index: 0.9272757250072924
    legacy_id: v001
  I3CN8543:
    source_metadata:
      id: http://purl.bdrc.io/resource/I3CN8543
      total_pages: 490
      volume_number: 3
      volume_pages_bdrc_intro: 2
    order: 3
    base_file: I3CN8543.txt
    statistics:
      ocr_word_median_confidence_index: 0.9700000286102295
      ocr_word_mean_confidence_index: 0.9361349448319232
    legacy_id: v003
  I3CN8542:
    source_metadata:
      id: http://purl.bdrc.io/resource/I3CN8542
      total_pages: 480
      volume_number: 2
      volume_pages_bdrc_intro: 2
    order: 2
    base_file: I3CN8542.txt
    statistics:
      ocr_word_median_confidence_index: 0.9700000286102295
      ocr_word_mean_confidence_index: 0.9536871015569326
    legacy_id: v002
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
